# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d3d641d69affa2d21903ec602e98fef"
name = "storepulse"
application_url = "https://merchpulse.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "/api/webhooks"

[access_scopes]
scopes = "read_orders,read_products,read_customers,read_analytics,read_inventory"


[auth]
redirect_urls = ["https://merchpulse.vercel.app/api/auth/callback"]
